on:
  release:
    types: [created]

jobs:
  release:
    permissions: write-all
    name: release ${{ matrix.target }}
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            ext: ".exe"
            
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            ext: ""
            
          - target: x86_64-apple-darwin
            os: macos-latest
            ext: ""
            
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
          
      - name: Install ALSA
        run: sudo apt-get install -y alsa libasound2-dev
        if: contains(matrix.target, 'linux')

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.79
          target: ${{ matrix.target }}
        
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target-dir=/tmp

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /tmp/release/nebulizer${{ matrix.ext }}
          asset_name: nebulizer-${{ matrix.target }}${{ matrix.ext }}
          asset_content_type: application/octet-stream
